[package]
name = "inference-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.47.0", features = ["full"] }
# compio = { version = "0.18", features = ["runtime", "time", "net", "io"] }
# compio = { path = "../compio/compio", features = ["runtime", "time", "net", "io"]}
compio = { git = "https://github.com/compio-rs/compio", rev = "b06ff34caaa24c516821fe16da50191834524660", features = ["runtime", "time", "net", "io"] }
criterion = "0.5.1"
ort = { git = "https://github.com/pykeio/ort", rev = "76849504481c06c872c0b9450d39e8b9975c9b8e", features = [ "cuda", "load-dynamic"] }
ort-sys = { git = "https://github.com/pykeio/ort", rev = "76849504481c06c872c0b9450d39e8b9975c9b8e", default-features = false }
rand = "0.9.1"
futures = "0.3.31"
fusio = { version = "0.6", features = ["tokio-http", "aws"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
# GRPC Stuff
# pajamax = { path = "../pajamax/pajamax"}
pajamax = { git = "https://github.com/geobeau/pajamax", branch = "main" }
prost = "0.14"
prost-types = "0.14"
async-trait = "0.1"
local-sync = "0.1"
# console-subscriber = "0.4.1"
num-traits = "0.2.19"
arc-swap = "1.7.1"
atomic_refcell = "0.1"
bytemuck = "1.24.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
smallvec = "1.15.1"
hashbrown = "0.15"
prometheus = "0.13"
clap = { version = "4", features = ["derive"] }
core_affinity = "0.8"
mimalloc = { version = "0.1", default-features = false }

[profile.dev]
opt-level = 2
panic = 'abort'

[profile.release]
opt-level = 3
lto = true 
panic = 'abort'

[build-dependencies]
pajamax-build = { git = "https://github.com/geobeau/pajamax", branch = "main" }
prost-build = "0.14"
